name: Terraform Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Render user_data using console
        run: |
          terraform init
          terraform console <<EOF
          templatefile("${{ github.workspace }}/user_data.sh.tpl", {
            s3_bucket = "mybucket-name-here",
            domain_name = "my.server.com",
            admin_email = "my@email.com"
          })
          EOF

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
